import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import GeneratorCard from '../../../components/GeneratorCard';
import QuoteDrawer from '../../../components/QuoteDrawer';
import {generators,getGenerator,relatedGenerators} from '../../../data/generators';
export function generateStaticParams(){return generators.map(g=>({slug:g.slug}))}
export function generateMetadata({params}){const g=getGenerator(params.slug); return {title:g?`${g.seoTitle} | MKT Generators`:'Generator | MKT Generators',description:g?.seoDescription||''}}
export default function Detail({params}){const g=getGenerator(params.slug); if(!g) return <main><Header/><section className="page-hero"><h1>Generator not found</h1></section></main>;
 const rows={'Model':g.model,'Series':g.series,'Engine Brand':g.engineBrand,'Engine Model':g.engineModel,'Prime Power':`${g.primeKva} kVA`,'Standby Power':`${g.standbyKva} kVA`,'Frequency':g.frequency,'Voltage':g.voltage,'Controller':g.controller,'Cooling System':g.cooling,'Alternator':g.alternator,'Canopy Dimensions':g.dimensions?.canopy?`${g.dimensions.canopy.length} × ${g.dimensions.canopy.width} × ${g.dimensions.canopy.height} mm`:'To be confirmed','Open Dimensions':g.dimensions?.open?`${g.dimensions.open.length} × ${g.dimensions.open.width} × ${g.dimensions.open.height} mm`:'To be confirmed','Fuel Tank':g.dimensions?.canopy?.fuelTank?`${g.dimensions.canopy.fuelTank} L`:'To be confirmed'};
 return <main><Header/><section className="detail-hero"><div><span>{g.series} · {g.engineBrand}</span><h1>{g.model} Diesel Generator</h1><p>{g.primeKva} kVA Prime / {g.standbyKva} kVA Standby. Configurable as silent canopy or open type for industrial and export projects.</p><div className="hero-actions"><a href={`/datasheets/${g.slug}`}>View MKT Datasheet</a><a href="/rfq">Request Quote</a></div></div><img src={g.image} alt={g.model}/></section><section className="specs"><div className="section-head"><span>TECHNICAL DATA</span><h2>Specifications</h2><p>Public datasheet is rebranded as MKT. Source Full Generator branding is not shown.</p></div><table><tbody>{Object.entries(rows).map(([k,v])=><tr key={k}><th>{k}</th><td>{v}</td></tr>)}</tbody></table></section><section className="spec-tabs"><article><h3>Standard Features</h3><ul><li>Heavy-duty diesel engine</li><li>Deep Sea controller</li><li>Water cooling system</li><li>AVR controlled alternator</li><li>Emergency stop button</li><li>Anti-vibration mounts</li></ul></article><article><h3>Optional Equipment</h3><ul><li>ATS panel</li><li>Synchronization panel</li><li>Remote monitoring</li><li>External fuel tank</li><li>Super silent canopy</li><li>Mobile trailer package</li></ul></article></section><section className="catalog-preview"><div className="section-head"><span>RELATED</span><h2>Similar {g.engineBrand} Models</h2></div><div className="grid">{relatedGenerators(g).map(x=><GeneratorCard key={x.id} g={x}/>)}</div></section><QuoteDrawer/><Footer/></main>
}
